### ISSUE TITLE
LEDs resetting to full brightness on each cam0.led_dim()

### ISSUE THREAD

**Issue by shaun-ba** [miked63017/dinolite_uvc_led_control#3]
I added a quick argparse script to handle your module (not sure if this was the intended way to use it), but my problem is that every time i issue a command it "resets" the LEDs.

Example: Run "python led_control.py --dim down"

Returns: LED 5 Brightness

If i run the above again to take it to 4, it flashes (full brightness i assume), then returns "LED 5 Brightness" again.

```
parser = argparse.ArgumentParser(description='Dinolite LED Control')
parser.add_argument('--toggle', dest='toggle', action="store",
                    help='Toggle LEDs on or off')
parser.add_argument('--setdim', dest='setdim', action="store",
                    help='Dim LEDs, 1-6 Levels')
parser.add_argument('--getdim', dest='getdim', action="store_true",
                    help='Dim LEDs, 1-6 Levels')
parser.add_argument('--dim', dest='dim', action="store",
                    help='Dim LEDs, 1-6 Levels')
parser.add_argument('--ledtoggle', dest='ledtoggle', action="store",
                    help='Dim LEDs, 1-6 Levels')

args = parser.parse_args()

if args.toggle == "on":
	print("Turning LED on")
	cam0.led_on()

if args.toggle == "off":
	print("Turning LED off")
	cam0.led_off()

if args.dim == "down":
	cam0.led_dim()

if args.setdim:
	cam0.set_standard_control_value("Brightness", args.setdim)

if args.getdim:
	print(cam0.get_standard_control_value("Brightness"))

if args.ledtoggle:
	if args.ledtoggle == "1":
		cam0.toggle_led_1()
	if args.ledtoggle == "2":
		cam0.toggle_led_2()
	if args.ledtoggle == "3":
		cam0.toggle_led_3()
	if args.ledtoggle == "4":
		cam0.toggle_led_4()
	if args.ledtoggle == "5":
		cam0.toggle_led_5()
```

**Comment by miked63017** [comment]
Sorry for the delay in answering, for some reason I haven't been getting notifications on this repo. The script that is used from the command line is basically just a proof of concept, if you are doing anything in depth I would recommend using the module directly in a loop of sorts, basically if the script ends it loses state with the device and starts again next time you load the module. So if you want something long running I would run a loop that waits for user input, and respond to the input rather than running from the command line repeatedly since it won't stay connected that way. The "bin" script included here was really just for my testing purposes.
